// Auto-generated by VoxCraft Admin Panel - DO NOT EDIT MANUALLY
window.VoxCraftConfig = {
  FREE_CHAR_LIMIT:    10000,
  FREE_DAILY_ACTIONS: 8,
  FREE_BATCH_LIMIT:   4,
  FREE_PREVIEW_LIMIT: 6,
  FREE_VOICES_COUNT:  20,
  PRO_BATCH_MAX:      20,
  PRO_PRICE_PKR:      850,
  PRO_PRICE_LABEL:    '850 PKR',
  FREE_PRICE_LABEL:   'Free',
  CHECKOUT_URL:       'https://voxcraft.lemonsqueezy.com/checkout/buy/df774c8d-6327-4f03-abb3-5adfd1f1e7bb',
  FREE_FEATURES:      ['✓ All 9 audio tools','✓ 20 neural voices','✓ 10,000chars/month','✓ 10 actions/day','✗ Ads on generate','✗ 5 batch lines max'],
  PRO_FEATURES:       ['✓ All 9 tools unlimited','✓ All 70+ neural voices','✓ Unlimited characters','✓ Unlimited actions/day','✓ Zero ads','✓ Instant generation','✓ 20 batch lines'],
};
